2023-10-26 11:29:34,598 [DEBUG]  Sanic-CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'filename', 'supports_credentials': True, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2023-10-26 11:29:34,598 [DEBUG]  Available web server routes: 
/webhooks/rasa                                     GET                            rasa_core_no_api.custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           rasa_core_no_api.custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            rasa_core_no_api.custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           rasa_core_no_api.custom_webhook_RestInput.receive
/                                                  GET                            rasa_core_no_api.hello
2023-10-26 11:29:34,598 [INFO ]  Starting Rasa server on http://0.0.0.0:5005
2023-10-26 11:29:34,598 [DEBUG]  Using the default number of Sanic workers (1).
2023-10-26 11:29:34,724 [DEBUG]  Starting new HTTPS connection (1): api.segment.io:443
2023-10-26 11:29:35,617 [DEBUG]  https://api.segment.io:443 "POST /v1/track HTTP/1.1" 200 21
2023-10-26 11:29:35,656 [DEBUG]  Connected to InMemoryTrackerStore.
2023-10-26 11:29:35,657 [DEBUG]  Connected to lock store 'InMemoryLockStore'.
2023-10-26 11:29:35,658 [DEBUG]  Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2023-10-26 11:29:35,659 [INFO ]  Loading model models\20231026-112240-selfish-landform.tar.gz...
2023-10-26 11:29:35,716 [DEBUG]  Extracted model to 'C:\Users\Tanson\AppData\Local\Temp\tmpvdht65f2'.
2023-10-26 11:29:35,727 [DEBUG]  Node 'nlu_message_converter' loading 'NLUMessageConverter.load' and kwargs: '{}'.
2023-10-26 11:29:35,728 [DEBUG]  Node 'run_JiebaTokenizer0' loading 'JiebaTokenizer.load' and kwargs: '{}'.
2023-10-26 11:29:35,728 [DEBUG]  Node 'run_RegexFeaturizer1' loading 'RegexFeaturizer.load' and kwargs: '{}'.
2023-10-26 11:29:35,728 [DEBUG]  Resource 'train_RegexFeaturizer1' was requested for reading.
2023-10-26 11:29:35,729 [DEBUG]  Node 'run_LexicalSyntacticFeaturizer2' loading 'LexicalSyntacticFeaturizer.load' and kwargs: '{}'.
2023-10-26 11:29:35,729 [DEBUG]  Resource 'train_LexicalSyntacticFeaturizer2' was requested for reading.
2023-10-26 11:29:35,732 [DEBUG]  Node 'run_CountVectorsFeaturizer3' loading 'CountVectorsFeaturizer.load' and kwargs: '{}'.
2023-10-26 11:29:35,733 [DEBUG]  Resource 'train_CountVectorsFeaturizer3' was requested for reading.
2023-10-26 11:29:35,734 [DEBUG]  Node 'run_EntitySynonymMapper4' loading 'EntitySynonymMapper.load' and kwargs: '{}'.
2023-10-26 11:29:35,734 [DEBUG]  Resource 'train_EntitySynonymMapper4' was requested for reading.
2023-10-26 11:29:35,735 [DEBUG]  Node 'run_ResponseSelector5' loading 'ResponseSelector.load' and kwargs: '{}'.
2023-10-26 11:29:35,735 [DEBUG]  Resource 'train_ResponseSelector5' was requested for reading.
2023-10-26 11:29:35,736 [DEBUG]  Failed to load ABCMeta from model storage. Resource 'train_ResponseSelector5' doesn't exist.
2023-10-26 11:29:35,737 [DEBUG]  Resource 'train_ResponseSelector5' was requested for reading.
2023-10-26 11:29:35,737 [DEBUG]  Failed to load ResponseSelector from model storage. Resource 'train_ResponseSelector5' doesn't exist.
2023-10-26 11:29:35,738 [DEBUG]  Node 'run_FallbackClassifier6' loading 'FallbackClassifier.load' and kwargs: '{}'.
2023-10-26 11:29:35,738 [DEBUG]  Node 'run_RegexEntityExtractor7' loading 'RegexEntityExtractor.load' and kwargs: '{}'.
2023-10-26 11:29:35,739 [DEBUG]  Resource 'train_RegexEntityExtractor7' was requested for reading.
2023-10-26 11:29:35,739 [DEBUG]  Node 'run_RegexMessageHandler' loading 'RegexMessageHandler.load' and kwargs: '{}'.
2023-10-26 11:29:35,739 [DEBUG]  Node 'domain_provider' loading 'DomainProvider.load' and kwargs: '{}'.
2023-10-26 11:29:35,740 [DEBUG]  Resource 'domain_provider' was requested for reading.
2023-10-26 11:29:35,758 [DEBUG]  Node 'run_RulePolicy0' loading 'RulePolicy.load' and kwargs: '{}'.
2023-10-26 11:29:35,758 [DEBUG]  Resource 'train_RulePolicy0' was requested for reading.
2023-10-26 11:29:35,760 [DEBUG]  Node 'run_TEDPolicy1' loading 'TEDPolicy.load' and kwargs: '{}'.
2023-10-26 11:29:35,760 [DEBUG]  Resource 'train_TEDPolicy1' was requested for reading.
2023-10-26 11:29:35,760 [DEBUG]  Loading the model from C:\Users\Tanson\AppData\Local\Temp\tmp2_d6vh_u\train_TEDPolicy1\ted_policy.tf_model with finetune_mode=False...
2023-10-26 11:29:47,383 [DEBUG]  Finished loading the model.
2023-10-26 11:29:47,383 [DEBUG]  Node 'rule_only_data_provider' loading 'RuleOnlyDataProvider.load' and kwargs: '{}'.
2023-10-26 11:29:47,384 [DEBUG]  Resource 'train_RulePolicy0' was requested for reading.
2023-10-26 11:29:47,385 [DEBUG]  Node 'select_prediction' loading 'DefaultPolicyPredictionEnsemble.load' and kwargs: '{}'.
2023-10-26 11:29:47,389 [INFO ]  Rasa server is up and running.
2023-10-26 11:29:47,391 [INFO ]  Enabling coroutine debugging. Loop id 2653857205072.
2023-10-26 11:32:38,550 [DEBUG]  Sanic-CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'filename', 'supports_credentials': True, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2023-10-26 11:32:38,552 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            rasa_core_no_api.custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           rasa_core_no_api.custom_webhook_CmdlineInput.receive
/                                                  GET                            rasa_core_no_api.hello
2023-10-26 11:32:38,553 [INFO ]  Starting Rasa server on http://0.0.0.0:5005
2023-10-26 11:32:38,554 [DEBUG]  Using the default number of Sanic workers (1).
2023-10-26 11:32:38,625 [DEBUG]  Starting new HTTPS connection (1): api.segment.io:443
2023-10-26 11:32:39,469 [DEBUG]  https://api.segment.io:443 "POST /v1/track HTTP/1.1" 200 21
2023-10-26 11:32:39,510 [DEBUG]  Connected to InMemoryTrackerStore.
2023-10-26 11:32:39,511 [DEBUG]  Connected to lock store 'InMemoryLockStore'.
2023-10-26 11:32:39,511 [DEBUG]  Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2023-10-26 11:32:39,512 [INFO ]  Loading model E:\课程\Rasa_final\models\20231026-112240-selfish-landform.tar.gz...
2023-10-26 11:32:39,561 [DEBUG]  Extracted model to 'C:\Users\Tanson\AppData\Local\Temp\tmpu9wmrej4'.
2023-10-26 11:32:39,571 [DEBUG]  Node 'nlu_message_converter' loading 'NLUMessageConverter.load' and kwargs: '{}'.
2023-10-26 11:32:39,571 [DEBUG]  Node 'run_JiebaTokenizer0' loading 'JiebaTokenizer.load' and kwargs: '{}'.
2023-10-26 11:32:39,572 [DEBUG]  Node 'run_RegexFeaturizer1' loading 'RegexFeaturizer.load' and kwargs: '{}'.
2023-10-26 11:32:39,572 [DEBUG]  Resource 'train_RegexFeaturizer1' was requested for reading.
2023-10-26 11:32:39,572 [DEBUG]  Node 'run_LexicalSyntacticFeaturizer2' loading 'LexicalSyntacticFeaturizer.load' and kwargs: '{}'.
2023-10-26 11:32:39,572 [DEBUG]  Resource 'train_LexicalSyntacticFeaturizer2' was requested for reading.
2023-10-26 11:32:39,577 [DEBUG]  Node 'run_CountVectorsFeaturizer3' loading 'CountVectorsFeaturizer.load' and kwargs: '{}'.
2023-10-26 11:32:39,578 [DEBUG]  Resource 'train_CountVectorsFeaturizer3' was requested for reading.
2023-10-26 11:32:39,578 [DEBUG]  Node 'run_EntitySynonymMapper4' loading 'EntitySynonymMapper.load' and kwargs: '{}'.
2023-10-26 11:32:39,579 [DEBUG]  Resource 'train_EntitySynonymMapper4' was requested for reading.
2023-10-26 11:32:39,580 [DEBUG]  Node 'run_ResponseSelector5' loading 'ResponseSelector.load' and kwargs: '{}'.
2023-10-26 11:32:39,580 [DEBUG]  Resource 'train_ResponseSelector5' was requested for reading.
2023-10-26 11:32:39,580 [DEBUG]  Failed to load ABCMeta from model storage. Resource 'train_ResponseSelector5' doesn't exist.
2023-10-26 11:32:39,581 [DEBUG]  Resource 'train_ResponseSelector5' was requested for reading.
2023-10-26 11:32:39,581 [DEBUG]  Failed to load ResponseSelector from model storage. Resource 'train_ResponseSelector5' doesn't exist.
2023-10-26 11:32:39,582 [DEBUG]  Node 'run_FallbackClassifier6' loading 'FallbackClassifier.load' and kwargs: '{}'.
2023-10-26 11:32:39,582 [DEBUG]  Node 'run_RegexEntityExtractor7' loading 'RegexEntityExtractor.load' and kwargs: '{}'.
2023-10-26 11:32:39,582 [DEBUG]  Resource 'train_RegexEntityExtractor7' was requested for reading.
2023-10-26 11:32:39,583 [DEBUG]  Node 'run_RegexMessageHandler' loading 'RegexMessageHandler.load' and kwargs: '{}'.
2023-10-26 11:32:39,583 [DEBUG]  Node 'domain_provider' loading 'DomainProvider.load' and kwargs: '{}'.
2023-10-26 11:32:39,583 [DEBUG]  Resource 'domain_provider' was requested for reading.
2023-10-26 11:32:39,600 [DEBUG]  Node 'run_RulePolicy0' loading 'RulePolicy.load' and kwargs: '{}'.
2023-10-26 11:32:39,600 [DEBUG]  Resource 'train_RulePolicy0' was requested for reading.
2023-10-26 11:32:39,609 [DEBUG]  Node 'run_TEDPolicy1' loading 'TEDPolicy.load' and kwargs: '{}'.
2023-10-26 11:32:39,609 [DEBUG]  Resource 'train_TEDPolicy1' was requested for reading.
2023-10-26 11:32:39,616 [DEBUG]  Loading the model from C:\Users\Tanson\AppData\Local\Temp\tmp1kxrlqos\train_TEDPolicy1\ted_policy.tf_model with finetune_mode=False...
2023-10-26 11:32:49,814 [DEBUG]  Finished loading the model.
2023-10-26 11:32:49,814 [DEBUG]  Node 'rule_only_data_provider' loading 'RuleOnlyDataProvider.load' and kwargs: '{}'.
2023-10-26 11:32:49,815 [DEBUG]  Resource 'train_RulePolicy0' was requested for reading.
2023-10-26 11:32:49,816 [DEBUG]  Node 'select_prediction' loading 'DefaultPolicyPredictionEnsemble.load' and kwargs: '{}'.
2023-10-26 11:32:49,820 [INFO ]  Rasa server is up and running.
2023-10-26 11:32:49,821 [INFO ]  Enabling coroutine debugging. Loop id 2460124938144.
2023-10-26 11:33:39,193 [INFO ]  Killing Sanic server now.
2023-10-26 11:33:39,350 [ERROR]  Task was destroyed but it is pending!
task: <Task pending name='Task-6' coro=<ctrlc_workaround_for_windows.<locals>.stay_active() running at D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\compat.py:79> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x0000023CCC4CCFD0>()] created at D:\Anaconda3\envs\RasaEnv\lib\asyncio\base_events.py:429>>
2023-10-26 11:35:26,068 [DEBUG]  Sanic-CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'filename', 'supports_credentials': True, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2023-10-26 11:35:26,071 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            rasa_core_no_api.custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           rasa_core_no_api.custom_webhook_CmdlineInput.receive
/                                                  GET                            rasa_core_no_api.hello
2023-10-26 11:35:26,072 [INFO ]  Starting Rasa server on http://0.0.0.0:5005
2023-10-26 11:35:26,072 [DEBUG]  Using the default number of Sanic workers (1).
2023-10-26 11:35:26,148 [DEBUG]  Starting new HTTPS connection (1): api.segment.io:443
2023-10-26 11:35:27,054 [DEBUG]  https://api.segment.io:443 "POST /v1/track HTTP/1.1" 200 21
2023-10-26 11:35:27,097 [DEBUG]  Connected to InMemoryTrackerStore.
2023-10-26 11:35:27,098 [DEBUG]  Connected to lock store 'InMemoryLockStore'.
2023-10-26 11:35:27,098 [DEBUG]  Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2023-10-26 11:35:27,099 [INFO ]  Loading model E:\课程\Rasa_final\models\20231026-113401-speedy-pascal.tar.gz...
2023-10-26 11:35:27,147 [DEBUG]  Extracted model to 'C:\Users\Tanson\AppData\Local\Temp\tmpvvmu3e0t'.
2023-10-26 11:35:27,161 [DEBUG]  Node 'nlu_message_converter' loading 'NLUMessageConverter.load' and kwargs: '{}'.
2023-10-26 11:35:27,162 [DEBUG]  Node 'run_JiebaTokenizer0' loading 'JiebaTokenizer.load' and kwargs: '{}'.
2023-10-26 11:35:27,162 [DEBUG]  Node 'run_RegexFeaturizer1' loading 'RegexFeaturizer.load' and kwargs: '{}'.
2023-10-26 11:35:27,162 [DEBUG]  Resource 'train_RegexFeaturizer1' was requested for reading.
2023-10-26 11:35:27,163 [DEBUG]  Node 'run_LexicalSyntacticFeaturizer2' loading 'LexicalSyntacticFeaturizer.load' and kwargs: '{}'.
2023-10-26 11:35:27,163 [DEBUG]  Resource 'train_LexicalSyntacticFeaturizer2' was requested for reading.
2023-10-26 11:35:27,167 [DEBUG]  Node 'run_CountVectorsFeaturizer3' loading 'CountVectorsFeaturizer.load' and kwargs: '{}'.
2023-10-26 11:35:27,167 [DEBUG]  Resource 'train_CountVectorsFeaturizer3' was requested for reading.
2023-10-26 11:35:27,169 [DEBUG]  Node 'run_EntitySynonymMapper4' loading 'EntitySynonymMapper.load' and kwargs: '{}'.
2023-10-26 11:35:27,169 [DEBUG]  Resource 'train_EntitySynonymMapper4' was requested for reading.
2023-10-26 11:35:27,170 [DEBUG]  Node 'run_ResponseSelector5' loading 'ResponseSelector.load' and kwargs: '{}'.
2023-10-26 11:35:27,170 [DEBUG]  Resource 'train_ResponseSelector5' was requested for reading.
2023-10-26 11:35:27,171 [DEBUG]  Failed to load ABCMeta from model storage. Resource 'train_ResponseSelector5' doesn't exist.
2023-10-26 11:35:27,172 [DEBUG]  Resource 'train_ResponseSelector5' was requested for reading.
2023-10-26 11:35:27,172 [DEBUG]  Failed to load ResponseSelector from model storage. Resource 'train_ResponseSelector5' doesn't exist.
2023-10-26 11:35:27,173 [DEBUG]  Node 'run_FallbackClassifier6' loading 'FallbackClassifier.load' and kwargs: '{}'.
2023-10-26 11:35:27,173 [DEBUG]  Node 'run_RegexEntityExtractor7' loading 'RegexEntityExtractor.load' and kwargs: '{}'.
2023-10-26 11:35:27,173 [DEBUG]  Resource 'train_RegexEntityExtractor7' was requested for reading.
2023-10-26 11:35:27,174 [DEBUG]  Node 'run_RegexMessageHandler' loading 'RegexMessageHandler.load' and kwargs: '{}'.
2023-10-26 11:35:27,174 [DEBUG]  Node 'domain_provider' loading 'DomainProvider.load' and kwargs: '{}'.
2023-10-26 11:35:27,175 [DEBUG]  Resource 'domain_provider' was requested for reading.
2023-10-26 11:35:27,193 [DEBUG]  Node 'run_RulePolicy0' loading 'RulePolicy.load' and kwargs: '{}'.
2023-10-26 11:35:27,193 [DEBUG]  Resource 'train_RulePolicy0' was requested for reading.
2023-10-26 11:35:27,198 [DEBUG]  Node 'run_TEDPolicy1' loading 'TEDPolicy.load' and kwargs: '{}'.
2023-10-26 11:35:27,198 [DEBUG]  Resource 'train_TEDPolicy1' was requested for reading.
2023-10-26 11:35:27,205 [DEBUG]  Loading the model from C:\Users\Tanson\AppData\Local\Temp\tmpxxpzhq1k\train_TEDPolicy1\ted_policy.tf_model with finetune_mode=False...
2023-10-26 11:35:39,593 [DEBUG]  Finished loading the model.
2023-10-26 11:35:39,593 [DEBUG]  Node 'rule_only_data_provider' loading 'RuleOnlyDataProvider.load' and kwargs: '{}'.
2023-10-26 11:35:39,593 [DEBUG]  Resource 'train_RulePolicy0' was requested for reading.
2023-10-26 11:35:39,595 [DEBUG]  Node 'select_prediction' loading 'DefaultPolicyPredictionEnsemble.load' and kwargs: '{}'.
2023-10-26 11:35:39,604 [INFO ]  Rasa server is up and running.
2023-10-26 11:35:39,606 [INFO ]  Enabling coroutine debugging. Loop id 2128614548576.
2023-10-26 11:36:11,877 [DEBUG]  Issuing ticket for conversation '9c7161dd2957403189102be38fb76db6'.
2023-10-26 11:36:11,878 [DEBUG]  Acquiring lock for conversation '9c7161dd2957403189102be38fb76db6'.
2023-10-26 11:36:11,878 [DEBUG]  Acquired lock for conversation '9c7161dd2957403189102be38fb76db6'.
2023-10-26 11:36:11,878 [DEBUG]  Could not find tracker for conversation ID '9c7161dd2957403189102be38fb76db6'.
2023-10-26 11:36:11,879 [DEBUG]  No event broker configured. Skipping streaming events.
2023-10-26 11:36:11,879 [DEBUG]  Starting a new session for conversation ID '9c7161dd2957403189102be38fb76db6'.
2023-10-26 11:36:11,881 [DEBUG]  [[32m[1mdebug    [0m] [1mprocessor.actions.policy_prediction[0m [36mprediction_events[0m=[35m[][0m
2023-10-26 11:36:11,882 [DEBUG]  [[32m[1mdebug    [0m] [1mprocessor.actions.log         [0m [36maction_name[0m=[35maction_session_start[0m [36mrasa_events[0m=[35m[<rasa.shared.core.events.SessionStarted object at 0x000001EF9BA45E50>, ActionExecuted(action: action_listen, policy: None, confidence: None)][0m
2023-10-26 11:36:11,882 [DEBUG]  [[32m[1mdebug    [0m] [1mprocessor.slots.log           [0m [36mslot_values[0m=[35m	session_started_metadata: None[0m
2023-10-26 11:36:11,882 [DEBUG]  Running graph with inputs: {'__message__': [<rasa.core.channels.channel.UserMessage object at 0x000001EF9BB09550>], '__tracker__': <rasa.shared.core.trackers.DialogueStateTracker object at 0x000001EF9BB09430>}, targets: ['run_RegexMessageHandler'] and ExecutionContext(model_id='bb63d02bacbd4c0a947e7ed875a697e7', should_add_diagnostic_data=False, is_finetuning=False, node_name=None).
2023-10-26 11:36:11,883 [DEBUG]  Node 'nlu_message_converter' running 'NLUMessageConverter.convert_user_message'.
2023-10-26 11:36:11,884 [DEBUG]  Node 'run_JiebaTokenizer0' running 'JiebaTokenizer.process'.
2023-10-26 11:36:11,897 [DEBUG]  Building prefix dict from the default dictionary ...
2023-10-26 11:36:11,897 [DEBUG]  Loading model from cache C:\Users\Tanson\AppData\Local\Temp\jieba.cache
2023-10-26 11:36:12,376 [DEBUG]  Loading model cost 0.479 seconds.
2023-10-26 11:36:12,376 [DEBUG]  Prefix dict has been built successfully.
2023-10-26 11:36:12,377 [DEBUG]  Node 'run_RegexFeaturizer1' running 'RegexFeaturizer.process'.
2023-10-26 11:36:12,377 [DEBUG]  Node 'run_LexicalSyntacticFeaturizer2' running 'LexicalSyntacticFeaturizer.process'.
2023-10-26 11:36:12,378 [DEBUG]  Node 'run_CountVectorsFeaturizer3' running 'CountVectorsFeaturizer.process'.
2023-10-26 11:36:12,379 [DEBUG]  Node 'run_EntitySynonymMapper4' running 'EntitySynonymMapper.process'.
2023-10-26 11:36:12,379 [DEBUG]  Node 'run_ResponseSelector5' running 'ResponseSelector.process'.
2023-10-26 11:36:12,380 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2023-10-26 11:36:12,380 [DEBUG]  Adding following selector key to message property: default
2023-10-26 11:36:12,380 [DEBUG]  Node 'run_FallbackClassifier6' running 'FallbackClassifier.process'.
2023-10-26 11:36:12,381 [DEBUG]  Deleted lock for conversation '9c7161dd2957403189102be38fb76db6'.
2023-10-26 11:37:12,066 [ERROR]  Task exception was never retrieved
future: <Task finished name='Task-76' coro=<RestInput.on_message_wrapper() done, defined at D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\rest.py:37> exception=GraphComponentException('Error running graph component for node run_FallbackClassifier6.') created at D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\rest.py:106>
source_traceback: Object created at (most recent call last):
  File "D:\Anaconda3\envs\RasaEnv\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\RasaEnv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\RasaEnv\Scripts\rasa.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\__main__.py", line 133, in main
    cmdline_arguments.func(cmdline_arguments)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\cli\shell.py", line 141, in shell
    rasa.cli.run.run(args)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\cli\run.py", line 124, in run
    rasa.run(**vars(args))
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\api.py", line 56, in run
    rasa.core.run.serve_application(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\run.py", line 231, in serve_application
    app.run(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\app.py", line 1204, in run
    serve_single(server_settings)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\server\runners.py", line 206, in serve_single
    serve(**server_settings)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\server\runners.py", line 155, in serve
    loop.run_forever()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\base_events.py", line 1897, in _run_once
    handle._run()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "connection_task", line 15, in connection_task
    from sanic.http import Http, Stage
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\http.py", line 146, in http1
    await self.protocol.request_handler(self.request)
  File "handle_request", line 112, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\response.py", line 414, in stream
    await self.streaming_fn(self)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\rest.py", line 106, in stream
    task = asyncio.ensure_future(
Traceback (most recent call last):
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\engine\graph.py", line 487, in __call__
    output = self._fn(self._component, **run_kwargs)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\nlu\classifiers\fallback_classifier.py", line 87, in process
    if not self._should_fallback(message):
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\nlu\classifiers\fallback_classifier.py", line 108, in _should_fallback
    intent_name = message.data[INTENT].get(INTENT_NAME_KEY)
KeyError: 'intent'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\rest.py", line 51, in on_message_wrapper
    await on_new_message(message)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\channel.py", line 89, in handler
    await app.ctx.agent.handle_message(message)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\agent.py", line 419, in handle_message
    return await self.processor.handle_message(  # type: ignore[union-attr]
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\processor.py", line 153, in handle_message
    tracker = await self.log_message(message, should_save_tracker=False)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\processor.py", line 462, in log_message
    await self._handle_message_with_tracker(message, tracker)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\processor.py", line 775, in _handle_message_with_tracker
    parse_data = await self.parse_message(message, tracker)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\processor.py", line 720, in parse_message
    parse_data = self._parse_message_with_graph(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\processor.py", line 752, in _parse_message_with_graph
    results = self.graph_runner.run(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\engine\runner\dask.py", line 101, in run
    dask_result = dask.get(run_graph, run_targets)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 557, in get_sync
    return get_async(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 500, in get_async
    for key, res_info, failed in queue_get(queue).result():
  File "D:\Anaconda3\envs\RasaEnv\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\Anaconda3\envs\RasaEnv\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 542, in submit
    fut.set_result(fn(*args, **kwargs))
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 238, in batch_execute_tasks
    return [execute_task(*a) for a in it]
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 238, in <listcomp>
    return [execute_task(*a) for a in it]
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 229, in execute_task
    result = pack_exception(e, dumps)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\engine\graph.py", line 494, in __call__
    raise GraphComponentException(
rasa.engine.exceptions.GraphComponentException: Error running graph component for node run_FallbackClassifier6.
2023-10-26 11:37:12,101 [ERROR]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<SignalRouter._dispatch() done, defined at D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\signals.py:121> exception=ClientResponseError(RequestInfo(url=URL('http://localhost:5005/webhooks/rest/webhook?stream=true&token='), method='POST', headers=<CIMultiDictProxy('Host': 'localhost:5005', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.9 aiohttp/3.8.5', 'Content-Length': '145', 'Content-Type': 'application/json')>, real_url=URL('http://localhost:5005/webhooks/rest/webhook?stream=true&token=')), (), status=503, message='Service Unavailable', headers=<CIMultiDictProxy('Content-Length': '79', 'Connection': 'close', 'Content-Type': 'application/json')>) created at D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\signals.py:193>
source_traceback: Object created at (most recent call last):
  File "D:\Anaconda3\envs\RasaEnv\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\RasaEnv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\RasaEnv\Scripts\rasa.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\__main__.py", line 133, in main
    cmdline_arguments.func(cmdline_arguments)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\cli\shell.py", line 141, in shell
    rasa.cli.run.run(args)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\cli\run.py", line 124, in run
    rasa.run(**vars(args))
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\api.py", line 56, in run
    rasa.core.run.serve_application(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\run.py", line 231, in serve_application
    app.run(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\app.py", line 1204, in run
    serve_single(server_settings)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\server\runners.py", line 206, in serve_single
    serve(**server_settings)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\server\runners.py", line 151, in serve
    loop.run_until_complete(app._server_event("init", "after"))
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\base_events.py", line 1897, in _run_once
    handle._run()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\app.py", line 2000, in _server_event
    await self.dispatch(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\signals.py", line 191, in dispatch
    return await dispatch
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\signals.py", line 161, in _dispatch
    retval = await maybe_coroutine
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\app.py", line 1524, in _listener
    await maybe_coro
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\app.py", line 1575, in dispatch_delayed_tasks
    await app.dispatch(name, context={"app": app, "loop": loop})
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\signals.py", line 193, in dispatch
    task = asyncio.get_running_loop().create_task(dispatch)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\signals.py", line 161, in _dispatch
    retval = await maybe_coroutine
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\app.py", line 1581, in run_delayed_task
    await prepped
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\run.py", line 138, in run_cmdline_io
    await console.record_messages(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\console.py", line 218, in record_messages
    async for response in bot_responses_stream:
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\console.py", line 164, in _send_message_receive_stream
    async with session.post(url, json=payload, raise_for_status=True) as resp:
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\aiohttp\client.py", line 643, in _request
    resp.raise_for_status()
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\aiohttp\client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 503, message='Service Unavailable', url=URL('http://localhost:5005/webhooks/rest/webhook?stream=true&token=')
2023-10-26 11:43:05,557 [DEBUG]  Sanic-CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'filename', 'supports_credentials': True, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2023-10-26 11:43:05,561 [DEBUG]  Available web server routes: 
/webhooks/rest                                     GET                            rasa_core_no_api.custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           rasa_core_no_api.custom_webhook_CmdlineInput.receive
/                                                  GET                            rasa_core_no_api.hello
2023-10-26 11:43:05,562 [INFO ]  Starting Rasa server on http://0.0.0.0:5005
2023-10-26 11:43:05,562 [DEBUG]  Using the default number of Sanic workers (1).
2023-10-26 11:43:05,652 [DEBUG]  Starting new HTTPS connection (1): api.segment.io:443
2023-10-26 11:43:06,522 [DEBUG]  https://api.segment.io:443 "POST /v1/track HTTP/1.1" 200 21
2023-10-26 11:43:06,559 [DEBUG]  Connected to InMemoryTrackerStore.
2023-10-26 11:43:06,560 [DEBUG]  Connected to lock store 'InMemoryLockStore'.
2023-10-26 11:43:06,560 [DEBUG]  Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2023-10-26 11:43:06,560 [INFO ]  Loading model E:\课程\Rasa_final\models\20231026-113401-speedy-pascal.tar.gz...
2023-10-26 11:43:06,606 [DEBUG]  Extracted model to 'C:\Users\Tanson\AppData\Local\Temp\tmpvglk9eqx'.
2023-10-26 11:43:06,617 [DEBUG]  Node 'nlu_message_converter' loading 'NLUMessageConverter.load' and kwargs: '{}'.
2023-10-26 11:43:06,617 [DEBUG]  Node 'run_JiebaTokenizer0' loading 'JiebaTokenizer.load' and kwargs: '{}'.
2023-10-26 11:43:06,618 [DEBUG]  Node 'run_RegexFeaturizer1' loading 'RegexFeaturizer.load' and kwargs: '{}'.
2023-10-26 11:43:06,618 [DEBUG]  Resource 'train_RegexFeaturizer1' was requested for reading.
2023-10-26 11:43:06,618 [DEBUG]  Node 'run_LexicalSyntacticFeaturizer2' loading 'LexicalSyntacticFeaturizer.load' and kwargs: '{}'.
2023-10-26 11:43:06,619 [DEBUG]  Resource 'train_LexicalSyntacticFeaturizer2' was requested for reading.
2023-10-26 11:43:06,622 [DEBUG]  Node 'run_CountVectorsFeaturizer3' loading 'CountVectorsFeaturizer.load' and kwargs: '{}'.
2023-10-26 11:43:06,622 [DEBUG]  Resource 'train_CountVectorsFeaturizer3' was requested for reading.
2023-10-26 11:43:06,624 [DEBUG]  Node 'run_EntitySynonymMapper4' loading 'EntitySynonymMapper.load' and kwargs: '{}'.
2023-10-26 11:43:06,624 [DEBUG]  Resource 'train_EntitySynonymMapper4' was requested for reading.
2023-10-26 11:43:06,625 [DEBUG]  Node 'run_ResponseSelector5' loading 'ResponseSelector.load' and kwargs: '{}'.
2023-10-26 11:43:06,626 [DEBUG]  Resource 'train_ResponseSelector5' was requested for reading.
2023-10-26 11:43:06,626 [DEBUG]  Failed to load ABCMeta from model storage. Resource 'train_ResponseSelector5' doesn't exist.
2023-10-26 11:43:06,627 [DEBUG]  Resource 'train_ResponseSelector5' was requested for reading.
2023-10-26 11:43:06,627 [DEBUG]  Failed to load ResponseSelector from model storage. Resource 'train_ResponseSelector5' doesn't exist.
2023-10-26 11:43:06,628 [DEBUG]  Node 'run_FallbackClassifier6' loading 'FallbackClassifier.load' and kwargs: '{}'.
2023-10-26 11:43:06,628 [DEBUG]  Node 'run_RegexEntityExtractor7' loading 'RegexEntityExtractor.load' and kwargs: '{}'.
2023-10-26 11:43:06,628 [DEBUG]  Resource 'train_RegexEntityExtractor7' was requested for reading.
2023-10-26 11:43:06,629 [DEBUG]  Node 'run_RegexMessageHandler' loading 'RegexMessageHandler.load' and kwargs: '{}'.
2023-10-26 11:43:06,629 [DEBUG]  Node 'domain_provider' loading 'DomainProvider.load' and kwargs: '{}'.
2023-10-26 11:43:06,629 [DEBUG]  Resource 'domain_provider' was requested for reading.
2023-10-26 11:43:06,648 [DEBUG]  Node 'run_RulePolicy0' loading 'RulePolicy.load' and kwargs: '{}'.
2023-10-26 11:43:06,649 [DEBUG]  Resource 'train_RulePolicy0' was requested for reading.
2023-10-26 11:43:06,654 [DEBUG]  Node 'run_TEDPolicy1' loading 'TEDPolicy.load' and kwargs: '{}'.
2023-10-26 11:43:06,654 [DEBUG]  Resource 'train_TEDPolicy1' was requested for reading.
2023-10-26 11:43:06,663 [DEBUG]  Loading the model from C:\Users\Tanson\AppData\Local\Temp\tmpliq5u2j5\train_TEDPolicy1\ted_policy.tf_model with finetune_mode=False...
2023-10-26 11:43:17,335 [DEBUG]  Finished loading the model.
2023-10-26 11:43:17,336 [DEBUG]  Node 'rule_only_data_provider' loading 'RuleOnlyDataProvider.load' and kwargs: '{}'.
2023-10-26 11:43:17,337 [DEBUG]  Resource 'train_RulePolicy0' was requested for reading.
2023-10-26 11:43:17,337 [DEBUG]  Node 'select_prediction' loading 'DefaultPolicyPredictionEnsemble.load' and kwargs: '{}'.
2023-10-26 11:43:17,343 [INFO ]  Rasa server is up and running.
2023-10-26 11:43:17,344 [INFO ]  Enabling coroutine debugging. Loop id 2051204939680.
2023-10-26 11:43:42,187 [DEBUG]  Issuing ticket for conversation '922f0b26533d43d7a8c37b0a8f890b6e'.
2023-10-26 11:43:42,188 [DEBUG]  Acquiring lock for conversation '922f0b26533d43d7a8c37b0a8f890b6e'.
2023-10-26 11:43:42,188 [DEBUG]  Acquired lock for conversation '922f0b26533d43d7a8c37b0a8f890b6e'.
2023-10-26 11:43:42,188 [DEBUG]  Could not find tracker for conversation ID '922f0b26533d43d7a8c37b0a8f890b6e'.
2023-10-26 11:43:42,189 [DEBUG]  No event broker configured. Skipping streaming events.
2023-10-26 11:43:42,189 [DEBUG]  Starting a new session for conversation ID '922f0b26533d43d7a8c37b0a8f890b6e'.
2023-10-26 11:43:42,193 [DEBUG]  [[32m[1mdebug    [0m] [1mprocessor.actions.policy_prediction[0m [36mprediction_events[0m=[35m[][0m
2023-10-26 11:43:42,193 [DEBUG]  [[32m[1mdebug    [0m] [1mprocessor.actions.log         [0m [36maction_name[0m=[35maction_session_start[0m [36mrasa_events[0m=[35m[<rasa.shared.core.events.SessionStarted object at 0x000001DD96B71580>, ActionExecuted(action: action_listen, policy: None, confidence: None)][0m
2023-10-26 11:43:42,194 [DEBUG]  [[32m[1mdebug    [0m] [1mprocessor.slots.log           [0m [36mslot_values[0m=[35m	session_started_metadata: None[0m
2023-10-26 11:43:42,194 [DEBUG]  Running graph with inputs: {'__message__': [<rasa.core.channels.channel.UserMessage object at 0x000001DD96B47E50>], '__tracker__': <rasa.shared.core.trackers.DialogueStateTracker object at 0x000001DD96B472E0>}, targets: ['run_RegexMessageHandler'] and ExecutionContext(model_id='bb63d02bacbd4c0a947e7ed875a697e7', should_add_diagnostic_data=False, is_finetuning=False, node_name=None).
2023-10-26 11:43:42,195 [DEBUG]  Node 'nlu_message_converter' running 'NLUMessageConverter.convert_user_message'.
2023-10-26 11:43:42,195 [DEBUG]  Node 'run_JiebaTokenizer0' running 'JiebaTokenizer.process'.
2023-10-26 11:43:42,206 [DEBUG]  Building prefix dict from the default dictionary ...
2023-10-26 11:43:42,207 [DEBUG]  Loading model from cache C:\Users\Tanson\AppData\Local\Temp\jieba.cache
2023-10-26 11:43:42,697 [DEBUG]  Loading model cost 0.491 seconds.
2023-10-26 11:43:42,698 [DEBUG]  Prefix dict has been built successfully.
2023-10-26 11:43:42,699 [DEBUG]  Node 'run_RegexFeaturizer1' running 'RegexFeaturizer.process'.
2023-10-26 11:43:42,699 [DEBUG]  Node 'run_LexicalSyntacticFeaturizer2' running 'LexicalSyntacticFeaturizer.process'.
2023-10-26 11:43:42,700 [DEBUG]  Node 'run_CountVectorsFeaturizer3' running 'CountVectorsFeaturizer.process'.
2023-10-26 11:43:42,700 [DEBUG]  Node 'run_EntitySynonymMapper4' running 'EntitySynonymMapper.process'.
2023-10-26 11:43:42,701 [DEBUG]  Node 'run_ResponseSelector5' running 'ResponseSelector.process'.
2023-10-26 11:43:42,701 [DEBUG]  There is no trained model for 'ResponseSelector': The component is either not trained or didn't receive enough training data.
2023-10-26 11:43:42,701 [DEBUG]  Adding following selector key to message property: default
2023-10-26 11:43:42,701 [DEBUG]  Node 'run_FallbackClassifier6' running 'FallbackClassifier.process'.
2023-10-26 11:43:42,702 [DEBUG]  Deleted lock for conversation '922f0b26533d43d7a8c37b0a8f890b6e'.
2023-10-26 11:44:42,359 [ERROR]  Task exception was never retrieved
future: <Task finished name='Task-75' coro=<RestInput.on_message_wrapper() done, defined at D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\rest.py:37> exception=GraphComponentException('Error running graph component for node run_FallbackClassifier6.') created at D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\rest.py:106>
source_traceback: Object created at (most recent call last):
  File "D:\Anaconda3\envs\RasaEnv\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\RasaEnv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\RasaEnv\Scripts\rasa.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\__main__.py", line 133, in main
    cmdline_arguments.func(cmdline_arguments)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\cli\shell.py", line 141, in shell
    rasa.cli.run.run(args)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\cli\run.py", line 124, in run
    rasa.run(**vars(args))
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\api.py", line 56, in run
    rasa.core.run.serve_application(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\run.py", line 231, in serve_application
    app.run(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\app.py", line 1204, in run
    serve_single(server_settings)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\server\runners.py", line 206, in serve_single
    serve(**server_settings)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\server\runners.py", line 155, in serve
    loop.run_forever()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\base_events.py", line 1897, in _run_once
    handle._run()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "connection_task", line 15, in connection_task
    from sanic.http import Http, Stage
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\http.py", line 146, in http1
    await self.protocol.request_handler(self.request)
  File "handle_request", line 112, in handle_request
    from sanic_ext.extensions.base import Extension  # type: ignore
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\response.py", line 414, in stream
    await self.streaming_fn(self)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\rest.py", line 106, in stream
    task = asyncio.ensure_future(
Traceback (most recent call last):
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\engine\graph.py", line 487, in __call__
    output = self._fn(self._component, **run_kwargs)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\nlu\classifiers\fallback_classifier.py", line 87, in process
    if not self._should_fallback(message):
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\nlu\classifiers\fallback_classifier.py", line 108, in _should_fallback
    intent_name = message.data[INTENT].get(INTENT_NAME_KEY)
KeyError: 'intent'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\rest.py", line 51, in on_message_wrapper
    await on_new_message(message)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\channel.py", line 89, in handler
    await app.ctx.agent.handle_message(message)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\agent.py", line 419, in handle_message
    return await self.processor.handle_message(  # type: ignore[union-attr]
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\processor.py", line 153, in handle_message
    tracker = await self.log_message(message, should_save_tracker=False)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\processor.py", line 462, in log_message
    await self._handle_message_with_tracker(message, tracker)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\processor.py", line 775, in _handle_message_with_tracker
    parse_data = await self.parse_message(message, tracker)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\processor.py", line 720, in parse_message
    parse_data = self._parse_message_with_graph(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\processor.py", line 752, in _parse_message_with_graph
    results = self.graph_runner.run(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\engine\runner\dask.py", line 101, in run
    dask_result = dask.get(run_graph, run_targets)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 557, in get_sync
    return get_async(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 500, in get_async
    for key, res_info, failed in queue_get(queue).result():
  File "D:\Anaconda3\envs\RasaEnv\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "D:\Anaconda3\envs\RasaEnv\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 542, in submit
    fut.set_result(fn(*args, **kwargs))
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 238, in batch_execute_tasks
    return [execute_task(*a) for a in it]
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 238, in <listcomp>
    return [execute_task(*a) for a in it]
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 229, in execute_task
    result = pack_exception(e, dumps)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\local.py", line 224, in execute_task
    result = _execute_task(task, data)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\dask\core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\engine\graph.py", line 494, in __call__
    raise GraphComponentException(
rasa.engine.exceptions.GraphComponentException: Error running graph component for node run_FallbackClassifier6.
2023-10-26 11:44:42,369 [ERROR]  Task exception was never retrieved
future: <Task finished name='Task-9' coro=<SignalRouter._dispatch() done, defined at D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\signals.py:121> exception=ClientResponseError(RequestInfo(url=URL('http://localhost:5005/webhooks/rest/webhook?stream=true&token='), method='POST', headers=<CIMultiDictProxy('Host': 'localhost:5005', 'Accept': '*/*', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.9 aiohttp/3.8.5', 'Content-Length': '145', 'Content-Type': 'application/json')>, real_url=URL('http://localhost:5005/webhooks/rest/webhook?stream=true&token=')), (), status=503, message='Service Unavailable', headers=<CIMultiDictProxy('Content-Length': '79', 'Connection': 'close', 'Content-Type': 'application/json')>) created at D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\signals.py:193>
source_traceback: Object created at (most recent call last):
  File "D:\Anaconda3\envs\RasaEnv\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Anaconda3\envs\RasaEnv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\RasaEnv\Scripts\rasa.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\__main__.py", line 133, in main
    cmdline_arguments.func(cmdline_arguments)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\cli\shell.py", line 141, in shell
    rasa.cli.run.run(args)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\cli\run.py", line 124, in run
    rasa.run(**vars(args))
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\api.py", line 56, in run
    rasa.core.run.serve_application(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\run.py", line 231, in serve_application
    app.run(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\app.py", line 1204, in run
    serve_single(server_settings)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\server\runners.py", line 206, in serve_single
    serve(**server_settings)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\server\runners.py", line 151, in serve
    loop.run_until_complete(app._server_event("init", "after"))
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\base_events.py", line 1897, in _run_once
    handle._run()
  File "D:\Anaconda3\envs\RasaEnv\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\app.py", line 2000, in _server_event
    await self.dispatch(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\signals.py", line 191, in dispatch
    return await dispatch
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\signals.py", line 161, in _dispatch
    retval = await maybe_coroutine
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\app.py", line 1524, in _listener
    await maybe_coro
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\app.py", line 1575, in dispatch_delayed_tasks
    await app.dispatch(name, context={"app": app, "loop": loop})
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\signals.py", line 193, in dispatch
    task = asyncio.get_running_loop().create_task(dispatch)
Traceback (most recent call last):
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\signals.py", line 161, in _dispatch
    retval = await maybe_coroutine
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\sanic\app.py", line 1581, in run_delayed_task
    await prepped
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\run.py", line 138, in run_cmdline_io
    await console.record_messages(
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\console.py", line 218, in record_messages
    async for response in bot_responses_stream:
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\rasa\core\channels\console.py", line 164, in _send_message_receive_stream
    async with session.post(url, json=payload, raise_for_status=True) as resp:
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\aiohttp\client.py", line 643, in _request
    resp.raise_for_status()
  File "D:\Anaconda3\envs\RasaEnv\lib\site-packages\aiohttp\client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 503, message='Service Unavailable', url=URL('http://localhost:5005/webhooks/rest/webhook?stream=true&token=')
